
version: '3'
services:
  redis:
    image: redis:7.4.0

  chap:
    build:
        context: .
        dockerfile: Dockerfile.test

    # multine command
    command: ["pytest", "/app/tests/"]

    container_name: chap_test

  #chap_with_r_inla:
  #  # multine command
  #  command: >
  #      echo "hello"
