services:
  chap:
    command: /app/.venv/bin/chap serve --auto-reload
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./logs:/app/logs
      - ./chap_core:/app/chap_core
      - ./tests:/app/tests
      - ./example_data:/app/example_data
      - ./external_models:/app/external_models
  worker:
    volumes:
      - ./logs:/app/logs
      - ./chap_core:/app/chap_core