services:
  chap:
    volumes:
      - ./chap_core:/app/chap_core
      - ./alembic:/app/alembic
      - ./config:/app/config
      - ./gunicorn.conf.py:/app/gunicorn.conf.py
  worker:
    volumes:
      # - ./logs:/app/logs
      - ./chap_core:/app/chap_core
      - ./alembic:/app/alembic
  postgres:
    ports:
      - "5432:5432"
