services:
  chap:
    build:
        context: .
        dockerfile: Dockerfile.test

    # multine command
    command: ["pytest", "/app/tests/"]
    depends_on:
        -  worker
    container_name: chap_test

  #chap_with_r_inla:
  #  # multine command
  #  command: >
  #      echo "hello"
