# This file defines models that will be available through the REST API, 
# which means they get aceessible through the Modeling app.
# models should point to a github repo, ideally specifying a commit hash
# Models may also include user choices if the model allows them

weekly_ar_model: 
  url: https://github.com/knutdrand/weekly_ar_model@36a537dac138af428a4167b2a89eac7dafd5d762
  versions:
    v0: "@v0.0.1"
    v1: "@36a537dac138af428a4167b2a89eac7dafd5d762"
  config:
    additional_continuous_covariates:
      - rain
      - temperature
    user_options:
      n_iterations: 3
    


    
