user_option_values:
  weight_decay:
    values: [1e-6, 1e-5]
  max_epochs: [1, 2]
  learning_rate:
    min: 0.0001
    max: 0.01
    scale: log
  batch_size: [64]
  augmentations: [[]]
  context_length: [12]
  past_ratio: [0.2]

additional_continuous_covariates:
  - rainfall
  - mean_temperature