name: Upload to PyPI

on:
  workflow_run:
    workflows: ["Bump version"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --dev

      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
